<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latestmajor</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AgoraNET" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0-rc.1.25451.107" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Endwire.Core\EndWire.Core.csproj" />
    <ProjectReference Include="..\Endwire.Domain\EndWire.Domain.csproj" />
    <ProjectReference Include="..\Endwire.Infrastructure\EndWire.Infrastructure.csproj" />
  </ItemGroup>

</Project>
